name: public
named: {}
views:
  uesio/docs.home: true
  uesio/docs.topbar: true
collections: {}
routes:
  uesio/docs.article: true
  uesio/docs.home: true
files: {}
bots: {}
integrationActions: {}
allowallbots: false
allowallcollections: false
allowallviews: false
allowallroutes: false
allowallfiles: true
allowallintegrationactions: false
modifyallrecords: false
viewallrecords: false
